name: react-app-application
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node modules
        run: npm i
      - name: Build app
        run: npm run build
      - name: Create .vercel folder
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo {"orgId":"\$VERCEL_ORG_ID\","projectId":"\$VERCEL_PROJECT_ID\"} > project.json
      - name: Deploy on Vercel
        run: npm deploy
      - name: Complete
        run: echo 'project build success'