name: react-app-application
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node modules
        run: npm i
      - name: Build app
        run: npm run build
      - name: Complete
        run: echo 'project build success'